# Generated by Django 2.0.7 on 2018-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('hand_0_initial', models.CharField(max_length=38)),
                ('hand_1_initial', models.CharField(max_length=38)),
                ('hand_2_initial', models.CharField(max_length=38)),
                ('hand_3_initial', models.CharField(max_length=38)),
                ('trick_number', models.IntegerField()),
                ('hearts_played', models.BooleanField()),
                ('trick_1', models.CharField(max_length=13)),
                ('trick_2', models.CharField(max_length=13)),
                ('trick_3', models.CharField(max_length=13)),
                ('trick_4', models.CharField(max_length=13)),
                ('trick_5', models.CharField(max_length=13)),
                ('trick_6', models.CharField(max_length=13)),
                ('trick_7', models.CharField(max_length=13)),
                ('trick_8', models.CharField(max_length=13)),
                ('trick_9', models.CharField(max_length=13)),
                ('trick_10', models.CharField(max_length=13)),
                ('trick_11', models.CharField(max_length=13)),
                ('trick_12', models.CharField(max_length=13)),
                ('trick_13', models.CharField(max_length=13)),
            ],
        ),
    ]
