# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartsMainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='trick_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_10',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_11',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_12',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_13',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_8',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trick_9',
        ),
        migrations.AddField(
            model_name='game',
            name='trick_history',
            field=models.CharField(default='', max_length=117),
        ),
    ]
