# Generated by Django 2.0.7 on 2018-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartsMainApp', '0003_auto_20180726_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hand_0_initial',
            field=models.CharField(default='0000000000000', max_length=38),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_1_initial',
            field=models.CharField(default='0000000000000', max_length=38),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_2_initial',
            field=models.CharField(default='0000000000000', max_length=38),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_3_initial',
            field=models.CharField(default='0000000000000', max_length=38),
        ),
        migrations.AlterField(
            model_name='game',
            name='hearts_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='trick_number',
            field=models.IntegerField(default=0),
        ),
    ]
