# Generated by Django 2.0.7 on 2018-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartsMainApp', '0004_auto_20180726_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_num',
            field=models.IntegerField(default=0),
        ),
    ]
