# Generated by Django 2.0.7 on 2018-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartsMainApp', '0005_game_game_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hand_0_initial',
            field=models.CharField(default='0', max_length=26),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_1_initial',
            field=models.CharField(default='0', max_length=26),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_2_initial',
            field=models.CharField(default='0', max_length=26),
        ),
        migrations.AlterField(
            model_name='game',
            name='hand_3_initial',
            field=models.CharField(default='0', max_length=26),
        ),
    ]
